#ifndef BINKW32_EXPORTS_HEADER
#define BINKW32_EXPORTS_HEADER


/**
 * Generated by vpr-forward
 * Original File: binkw32.dll
 * Target File: binkw32.original.dll
**/


static constexpr const char f__BinkBufferBlit_12[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferBlit@12=binkw32.original.dll._BinkBufferBlit@12";
static constexpr const char f__BinkBufferCheckWinPos_12[82] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferCheckWinPos@12=binkw32.original.dll._BinkBufferCheckWinPos@12";
static constexpr const char f__BinkBufferClear_8[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferClear@8=binkw32.original.dll._BinkBufferClear@8";
static constexpr const char f__BinkBufferClose_4[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferClose@4=binkw32.original.dll._BinkBufferClose@4";
static constexpr const char f__BinkBufferGetDescription_4[86] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferGetDescription@4=binkw32.original.dll._BinkBufferGetDescription@4";
static constexpr const char f__BinkBufferGetError_0[74] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferGetError@0=binkw32.original.dll._BinkBufferGetError@0";
static constexpr const char f__BinkBufferLock_4[66] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferLock@4=binkw32.original.dll._BinkBufferLock@4";
static constexpr const char f__BinkBufferOpen_16[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferOpen@16=binkw32.original.dll._BinkBufferOpen@16";
static constexpr const char f__BinkBufferSetDirectDraw_8[84] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferSetDirectDraw@8=binkw32.original.dll._BinkBufferSetDirectDraw@8";
static constexpr const char f__BinkBufferSetHWND_8[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferSetHWND@8=binkw32.original.dll._BinkBufferSetHWND@8";
static constexpr const char f__BinkBufferSetOffset_12[78] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferSetOffset@12=binkw32.original.dll._BinkBufferSetOffset@12";
static constexpr const char f__BinkBufferSetResolution_12[86] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferSetResolution@12=binkw32.original.dll._BinkBufferSetResolution@12";
static constexpr const char f__BinkBufferSetScale_12[76] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferSetScale@12=binkw32.original.dll._BinkBufferSetScale@12";
static constexpr const char f__BinkBufferUnlock_4[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkBufferUnlock@4=binkw32.original.dll._BinkBufferUnlock@4";
static constexpr const char f__BinkCheckCursor_20[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkCheckCursor@20=binkw32.original.dll._BinkCheckCursor@20";
static constexpr const char f__BinkClose_4[56] __attribute__(( section(".drectve"), used )) = " -export:_BinkClose@4=binkw32.original.dll._BinkClose@4";
static constexpr const char f__BinkCloseTrack_4[66] __attribute__(( section(".drectve"), used )) = " -export:_BinkCloseTrack@4=binkw32.original.dll._BinkCloseTrack@4";
static constexpr const char f__BinkCopyToBuffer_28[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkCopyToBuffer@28=binkw32.original.dll._BinkCopyToBuffer@28";
static constexpr const char f__BinkCopyToBufferRect_44[80] __attribute__(( section(".drectve"), used )) = " -export:_BinkCopyToBufferRect@44=binkw32.original.dll._BinkCopyToBufferRect@44";
static constexpr const char f__BinkDDSurfaceType_4[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkDDSurfaceType@4=binkw32.original.dll._BinkDDSurfaceType@4";
static constexpr const char f__BinkDX8SurfaceType_4[74] __attribute__(( section(".drectve"), used )) = " -export:_BinkDX8SurfaceType@4=binkw32.original.dll._BinkDX8SurfaceType@4";
static constexpr const char f__BinkDX9SurfaceType_4[74] __attribute__(( section(".drectve"), used )) = " -export:_BinkDX9SurfaceType@4=binkw32.original.dll._BinkDX9SurfaceType@4";
static constexpr const char f__BinkDoFrame_4[60] __attribute__(( section(".drectve"), used )) = " -export:_BinkDoFrame@4=binkw32.original.dll._BinkDoFrame@4";
static constexpr const char f__BinkGetError_0[62] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetError@0=binkw32.original.dll._BinkGetError@0";
static constexpr const char f__BinkGetKeyFrame_12[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetKeyFrame@12=binkw32.original.dll._BinkGetKeyFrame@12";
static constexpr const char f__BinkGetRealtime_12[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetRealtime@12=binkw32.original.dll._BinkGetRealtime@12";
static constexpr const char f__BinkGetRects_8[62] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetRects@8=binkw32.original.dll._BinkGetRects@8";
static constexpr const char f__BinkGetSummary_8[66] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetSummary@8=binkw32.original.dll._BinkGetSummary@8";
static constexpr const char f__BinkGetTrackData_8[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetTrackData@8=binkw32.original.dll._BinkGetTrackData@8";
static constexpr const char f__BinkGetTrackID_8[66] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetTrackID@8=binkw32.original.dll._BinkGetTrackID@8";
static constexpr const char f__BinkGetTrackMaxSize_8[76] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetTrackMaxSize@8=binkw32.original.dll._BinkGetTrackMaxSize@8";
static constexpr const char f__BinkGetTrackType_8[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkGetTrackType@8=binkw32.original.dll._BinkGetTrackType@8";
static constexpr const char f__BinkGoto_12[56] __attribute__(( section(".drectve"), used )) = " -export:_BinkGoto@12=binkw32.original.dll._BinkGoto@12";
static constexpr const char f__BinkIsSoftwareCursor_8[78] __attribute__(( section(".drectve"), used )) = " -export:_BinkIsSoftwareCursor@8=binkw32.original.dll._BinkIsSoftwareCursor@8";
static constexpr const char f__BinkLogoAddress_0[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkLogoAddress@0=binkw32.original.dll._BinkLogoAddress@0";
static constexpr const char f__BinkNextFrame_4[64] __attribute__(( section(".drectve"), used )) = " -export:_BinkNextFrame@4=binkw32.original.dll._BinkNextFrame@4";
static constexpr const char f__BinkOpen_8[54] __attribute__(( section(".drectve"), used )) = " -export:_BinkOpen@8=binkw32.original.dll._BinkOpen@8";
static constexpr const char f__BinkOpenDirectSound_4[76] __attribute__(( section(".drectve"), used )) = " -export:_BinkOpenDirectSound@4=binkw32.original.dll._BinkOpenDirectSound@4";
static constexpr const char f__BinkOpenMiles_4[64] __attribute__(( section(".drectve"), used )) = " -export:_BinkOpenMiles@4=binkw32.original.dll._BinkOpenMiles@4";
static constexpr const char f__BinkOpenTrack_8[64] __attribute__(( section(".drectve"), used )) = " -export:_BinkOpenTrack@8=binkw32.original.dll._BinkOpenTrack@8";
static constexpr const char f__BinkOpenWaveOut_4[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkOpenWaveOut@4=binkw32.original.dll._BinkOpenWaveOut@4";
static constexpr const char f__BinkPause_8[56] __attribute__(( section(".drectve"), used )) = " -export:_BinkPause@8=binkw32.original.dll._BinkPause@8";
static constexpr const char f__BinkRestoreCursor_4[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkRestoreCursor@4=binkw32.original.dll._BinkRestoreCursor@4";
static constexpr const char f__BinkService_4[60] __attribute__(( section(".drectve"), used )) = " -export:_BinkService@4=binkw32.original.dll._BinkService@4";
static constexpr const char f__BinkSetError_4[62] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetError@4=binkw32.original.dll._BinkSetError@4";
static constexpr const char f__BinkSetFrameRate_8[70] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetFrameRate@8=binkw32.original.dll._BinkSetFrameRate@8";
static constexpr const char f__BinkSetIO_4[56] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetIO@4=binkw32.original.dll._BinkSetIO@4";
static constexpr const char f__BinkSetIOSize_4[64] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetIOSize@4=binkw32.original.dll._BinkSetIOSize@4";
static constexpr const char f__BinkSetMemory_8[64] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetMemory@8=binkw32.original.dll._BinkSetMemory@8";
static constexpr const char f__BinkSetMixBinVolumes_20[80] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetMixBinVolumes@20=binkw32.original.dll._BinkSetMixBinVolumes@20";
static constexpr const char f__BinkSetMixBins_16[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetMixBins@16=binkw32.original.dll._BinkSetMixBins@16";
static constexpr const char f__BinkSetPan_12[60] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetPan@12=binkw32.original.dll._BinkSetPan@12";
static constexpr const char f__BinkSetSimulate_4[68] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetSimulate@4=binkw32.original.dll._BinkSetSimulate@4";
static constexpr const char f__BinkSetSoundOnOff_8[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetSoundOnOff@8=binkw32.original.dll._BinkSetSoundOnOff@8";
static constexpr const char f__BinkSetSoundSystem_8[74] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetSoundSystem@8=binkw32.original.dll._BinkSetSoundSystem@8";
static constexpr const char f__BinkSetSoundTrack_8[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetSoundTrack@8=binkw32.original.dll._BinkSetSoundTrack@8";
static constexpr const char f__BinkSetVideoOnOff_8[72] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetVideoOnOff@8=binkw32.original.dll._BinkSetVideoOnOff@8";
static constexpr const char f__BinkSetVolume_12[66] __attribute__(( section(".drectve"), used )) = " -export:_BinkSetVolume@12=binkw32.original.dll._BinkSetVolume@12";
static constexpr const char f__BinkWait_4[54] __attribute__(( section(".drectve"), used )) = " -export:_BinkWait@4=binkw32.original.dll._BinkWait@4";
static constexpr const char f__RADTimerRead_0[62] __attribute__(( section(".drectve"), used )) = " -export:_RADTimerRead@0=binkw32.original.dll._RADTimerRead@0";
static constexpr const char f__YUV_blit_16a1bpp_52[72] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16a1bpp@52=binkw32.original.dll._YUV_blit_16a1bpp@52";
static constexpr const char f__YUV_blit_16a1bpp_mask_60[82] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16a1bpp_mask@60=binkw32.original.dll._YUV_blit_16a1bpp_mask@60";
static constexpr const char f__YUV_blit_16a4bpp_52[72] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16a4bpp@52=binkw32.original.dll._YUV_blit_16a4bpp@52";
static constexpr const char f__YUV_blit_16a4bpp_mask_60[82] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16a4bpp_mask@60=binkw32.original.dll._YUV_blit_16a4bpp_mask@60";
static constexpr const char f__YUV_blit_16bpp_52[68] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16bpp@52=binkw32.original.dll._YUV_blit_16bpp@52";
static constexpr const char f__YUV_blit_16bpp_mask_60[78] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_16bpp_mask@60=binkw32.original.dll._YUV_blit_16bpp_mask@60";
static constexpr const char f__YUV_blit_24bpp_52[68] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_24bpp@52=binkw32.original.dll._YUV_blit_24bpp@52";
static constexpr const char f__YUV_blit_24bpp_mask_60[78] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_24bpp_mask@60=binkw32.original.dll._YUV_blit_24bpp_mask@60";
static constexpr const char f__YUV_blit_24rbpp_52[70] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_24rbpp@52=binkw32.original.dll._YUV_blit_24rbpp@52";
static constexpr const char f__YUV_blit_24rbpp_mask_60[80] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_24rbpp_mask@60=binkw32.original.dll._YUV_blit_24rbpp_mask@60";
static constexpr const char f__YUV_blit_32abpp_52[70] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32abpp@52=binkw32.original.dll._YUV_blit_32abpp@52";
static constexpr const char f__YUV_blit_32abpp_mask_60[80] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32abpp_mask@60=binkw32.original.dll._YUV_blit_32abpp_mask@60";
static constexpr const char f__YUV_blit_32bpp_52[68] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32bpp@52=binkw32.original.dll._YUV_blit_32bpp@52";
static constexpr const char f__YUV_blit_32bpp_mask_60[78] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32bpp_mask@60=binkw32.original.dll._YUV_blit_32bpp_mask@60";
static constexpr const char f__YUV_blit_32rabpp_52[72] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32rabpp@52=binkw32.original.dll._YUV_blit_32rabpp@52";
static constexpr const char f__YUV_blit_32rabpp_mask_60[82] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32rabpp_mask@60=binkw32.original.dll._YUV_blit_32rabpp_mask@60";
static constexpr const char f__YUV_blit_32rbpp_52[70] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32rbpp@52=binkw32.original.dll._YUV_blit_32rbpp@52";
static constexpr const char f__YUV_blit_32rbpp_mask_60[80] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_32rbpp_mask@60=binkw32.original.dll._YUV_blit_32rbpp_mask@60";
static constexpr const char f__YUV_blit_UYVY_52[66] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_UYVY@52=binkw32.original.dll._YUV_blit_UYVY@52";
static constexpr const char f__YUV_blit_UYVY_mask_60[76] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_UYVY_mask@60=binkw32.original.dll._YUV_blit_UYVY_mask@60";
static constexpr const char f__YUV_blit_YUY2_52[66] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_YUY2@52=binkw32.original.dll._YUV_blit_YUY2@52";
static constexpr const char f__YUV_blit_YUY2_mask_60[76] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_YUY2_mask@60=binkw32.original.dll._YUV_blit_YUY2_mask@60";
static constexpr const char f__YUV_blit_YV12_56[66] __attribute__(( section(".drectve"), used )) = " -export:_YUV_blit_YV12@56=binkw32.original.dll._YUV_blit_YV12@56";
static constexpr const char f__YUV_init_4[54] __attribute__(( section(".drectve"), used )) = " -export:_YUV_init@4=binkw32.original.dll._YUV_init@4";


#endif // BINKW32_EXPORTS_HEADER
